// <auto-generated />
namespace Book_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DBupdated_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBupdated_1));
        
        string IMigrationMetadata.Id
        {
            get { return "202308020940511_DBupdated_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
