// <auto-generated />
namespace Book_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BookStatusAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookStatusAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202309131053472_BookStatusAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
